<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EPPlus" Version="8.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ExcelWindow.WPF\ExcelWindow.WPF.csproj" />
    </ItemGroup>

</Project>
